sonar.projectKey=hiliving-frontend
sonar.projectName=Hiliving Mongolia Frontend
sonar.projectVersion=1.0
sonar.sources=frontend/src
sonar.tests=frontend/src
sonar.test.inclusions=frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx,frontend/src/test/**/*.ts
sonar.sourceEncoding=UTF-8
sonar.exclusions=frontend/src/**/*.d.ts,frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx,frontend/src/test/**,frontend/node_modules/**,frontend/dist/**
