ALTER TABLE orders DROP CONSTRAINT orders_status_valid;
ALTER TABLE orders DROP CONSTRAINT orders_payment_status_valid;
ALTER TABLE orders DROP CONSTRAINT orders_payment_method_valid;

ALTER TABLE orders ADD COLUMN inventory_released_at TIMESTAMPTZ;
ALTER TABLE orders ADD CONSTRAINT orders_status_valid CHECK (
    order_status IN ('PENDING_PAYMENT', 'PENDING_CONFIRMATION', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED')
);
ALTER TABLE orders ADD CONSTRAINT orders_payment_status_valid CHECK (
    payment_status IN ('UNPAID', 'PENDING', 'PAID', 'FAILED', 'EXPIRED', 'CANCELLED', 'REFUNDED')
);
ALTER TABLE orders ADD CONSTRAINT orders_payment_method_valid CHECK (
    payment_method IN ('CASH_ON_DELIVERY', 'QPAY')
);

CREATE TABLE payment_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    attempt_number INTEGER NOT NULL,
    sender_invoice_no VARCHAR(45) NOT NULL,
    provider_invoice_id VARCHAR(64),
    provider_payment_id VARCHAR(64),
    callback_token_hash VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    amount NUMERIC(14, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    qr_text TEXT,
    qr_image TEXT,
    short_url VARCHAR(2048),
    expires_at TIMESTAMPTZ NOT NULL,
    paid_at TIMESTAMPTZ,
    failure_code VARCHAR(80),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payment_attempts_order_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT payment_attempts_order_number_unique UNIQUE (order_id, attempt_number),
    CONSTRAINT payment_attempts_sender_invoice_unique UNIQUE (sender_invoice_no),
    CONSTRAINT payment_attempts_provider_invoice_unique UNIQUE (provider_invoice_id),
    CONSTRAINT payment_attempts_provider_payment_unique UNIQUE (provider_payment_id),
    CONSTRAINT payment_attempts_callback_hash_unique UNIQUE (callback_token_hash),
    CONSTRAINT payment_attempts_provider_valid CHECK (provider = 'QPAY'),
    CONSTRAINT payment_attempts_status_valid CHECK (
        status IN ('CREATED', 'AWAITING_PAYMENT', 'PAID', 'FAILED', 'EXPIRED', 'CANCELLED', 'REFUNDED', 'RECONCILIATION_REQUIRED')
    ),
    CONSTRAINT payment_attempts_amount_positive CHECK (amount > 0),
    CONSTRAINT payment_attempts_currency_valid CHECK (currency = 'MNT'),
    CONSTRAINT payment_attempts_hash_format CHECK (callback_token_hash ~ '^[0-9a-f]{64}$')
);

CREATE INDEX payment_attempts_order_created_idx ON payment_attempts (order_id, created_at DESC, id DESC);
CREATE INDEX payment_attempts_expiry_idx ON payment_attempts (expires_at, id)
    WHERE status IN ('CREATED', 'AWAITING_PAYMENT');

CREATE TABLE payment_deeplinks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_attempt_id BIGINT NOT NULL,
    display_order INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(120) NOT NULL,
    logo_url VARCHAR(2048) NOT NULL,
    link VARCHAR(4096) NOT NULL,
    CONSTRAINT payment_deeplinks_attempt_fkey FOREIGN KEY (payment_attempt_id) REFERENCES payment_attempts (id) ON DELETE CASCADE,
    CONSTRAINT payment_deeplinks_order_unique UNIQUE (payment_attempt_id, display_order),
    CONSTRAINT payment_deeplinks_display_nonnegative CHECK (display_order >= 0)
);

CREATE INDEX payment_deeplinks_attempt_idx ON payment_deeplinks (payment_attempt_id, display_order, id);
