CREATE TABLE content_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(80) NOT NULL UNIQUE,
    navigation_label VARCHAR(120) NOT NULL,
    title VARCHAR(240) NOT NULL,
    content_html TEXT NOT NULL DEFAULT '',
    published BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT content_pages_slug_format CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    CONSTRAINT content_pages_navigation_label_not_blank CHECK (char_length(btrim(navigation_label)) > 0),
    CONSTRAINT content_pages_title_not_blank CHECK (char_length(btrim(title)) > 0),
    CONSTRAINT content_pages_display_order_nonnegative CHECK (display_order >= 0)
);

CREATE UNIQUE INDEX content_pages_display_order_key ON content_pages (display_order);
CREATE INDEX content_pages_public_idx ON content_pages (display_order, id) WHERE published;

INSERT INTO content_pages (slug, navigation_label, title, content_html, published, display_order)
VALUES
    ('company-history', 'КОМПАНИЙН ТҮҮХ', 'Компанийн түүх', '', FALSE, 10),
    ('our-philosophy', 'БИДНИЙ ФИЛОСОФИ', 'Бидний философи', '', FALSE, 20),
    ('membership', 'ГИШҮҮНЧЛЭЛ', 'Гишүүнчлэл', '', FALSE, 30),
    ('awards', 'ШАГНАЛУУД', 'Шагналууд', '', FALSE, 40);

ALTER TABLE media_assets DROP CONSTRAINT media_assets_purpose_valid;
ALTER TABLE media_assets ADD CONSTRAINT media_assets_purpose_valid
    CHECK (purpose IN ('PRODUCT', 'BRAND', 'BANNER', 'NEWS', 'PAGE'));
