CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(160) NOT NULL,
    parent_id BIGINT,
    display_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT categories_slug_key UNIQUE (slug),
    CONSTRAINT categories_parent_fkey FOREIGN KEY (parent_id)
        REFERENCES categories (id) ON DELETE RESTRICT,
    CONSTRAINT categories_name_not_blank CHECK (char_length(btrim(name)) > 0),
    CONSTRAINT categories_slug_format CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    CONSTRAINT categories_display_order_nonnegative CHECK (display_order >= 0),
    CONSTRAINT categories_not_own_parent CHECK (parent_id IS NULL OR parent_id <> id)
);
CREATE INDEX categories_parent_id_idx ON categories (parent_id) WHERE parent_id IS NOT NULL;
CREATE INDEX categories_active_order_idx ON categories (display_order, name, id) WHERE active;

CREATE TABLE brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(160) NOT NULL,
    logo_url VARCHAR(2048),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT brands_pkey PRIMARY KEY (id),
    CONSTRAINT brands_slug_key UNIQUE (slug),
    CONSTRAINT brands_name_not_blank CHECK (char_length(btrim(name)) > 0),
    CONSTRAINT brands_slug_format CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    CONSTRAINT brands_logo_url_not_blank CHECK (logo_url IS NULL OR char_length(btrim(logo_url)) > 0)
);

CREATE INDEX brands_active_name_idx ON brands (name, id) WHERE active;

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(240) NOT NULL,
    slug VARCHAR(260) NOT NULL,
    short_description VARCHAR(500),
    description TEXT,
    price NUMERIC(12, 2) NOT NULL,
    discount_price NUMERIC(12, 2),
    category_id BIGINT NOT NULL,
    brand_id BIGINT,
    status VARCHAR(20) NOT NULL,
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT products_slug_key UNIQUE (slug),
    CONSTRAINT products_category_fkey FOREIGN KEY (category_id)
        REFERENCES categories (id) ON DELETE RESTRICT,
    CONSTRAINT products_brand_fkey FOREIGN KEY (brand_id)
        REFERENCES brands (id) ON DELETE SET NULL,
    CONSTRAINT products_name_not_blank CHECK (char_length(btrim(name)) > 0),
    CONSTRAINT products_slug_format CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    CONSTRAINT products_price_nonnegative CHECK (price >= 0),
    CONSTRAINT products_discount_price_valid CHECK (
        discount_price IS NULL OR (discount_price >= 0 AND discount_price < price)
    ),
    CONSTRAINT products_status_valid CHECK (status IN ('DRAFT', 'ACTIVE', 'ARCHIVED'))
);

CREATE INDEX products_category_status_idx ON products (category_id, status);
CREATE INDEX products_brand_status_idx ON products (brand_id, status) WHERE brand_id IS NOT NULL;
CREATE INDEX products_public_newest_idx ON products (created_at DESC, id DESC) WHERE status = 'ACTIVE';
CREATE INDEX products_public_price_idx ON products (price, id) WHERE status = 'ACTIVE';
CREATE INDEX products_public_featured_idx ON products (featured, created_at DESC, id DESC)
    WHERE status = 'ACTIVE';

CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    image_url VARCHAR(2048) NOT NULL,
    alt_text VARCHAR(255),
    display_order INTEGER NOT NULL DEFAULT 0,
    primary_image BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT product_images_pkey PRIMARY KEY (id),
    CONSTRAINT product_images_product_fkey FOREIGN KEY (product_id)
        REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT product_images_product_url_key UNIQUE (product_id, image_url),
    CONSTRAINT product_images_url_not_blank CHECK (char_length(btrim(image_url)) > 0),
    CONSTRAINT product_images_display_order_nonnegative CHECK (display_order >= 0)
);

CREATE INDEX product_images_product_order_idx ON product_images (product_id, display_order, id);
CREATE UNIQUE INDEX product_images_one_primary_idx ON product_images (product_id) WHERE primary_image;
