CREATE TABLE membership_tiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(20) NOT NULL,
    display_name VARCHAR(80) NOT NULL,
    default_discount_percentage NUMERIC(5, 2) NOT NULL,
    sort_order INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT membership_tiers_pkey PRIMARY KEY (id),
    CONSTRAINT membership_tiers_code_key UNIQUE (code),
    CONSTRAINT membership_tiers_code_valid CHECK (code IN ('REGULAR', 'BRONZE', 'SILVER', 'GOLD')),
    CONSTRAINT membership_tiers_name_not_blank CHECK (char_length(btrim(display_name)) > 0),
    CONSTRAINT membership_tiers_discount_valid CHECK (default_discount_percentage BETWEEN 0 AND 100),
    CONSTRAINT membership_tiers_sort_nonnegative CHECK (sort_order >= 0)
);

INSERT INTO membership_tiers (code, display_name, default_discount_percentage, sort_order)
VALUES
    ('REGULAR', 'Regular', 0.00, 0),
    ('BRONZE', 'Bronze', 3.00, 10),
    ('SILVER', 'Silver', 5.00, 20),
    ('GOLD', 'Gold', 10.00, 30);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL,
    phone_number VARCHAR(16) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    membership_tier_id BIGINT NOT NULL,
    discount_override_percentage NUMERIC(5, 2),
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    phone_verified BOOLEAN NOT NULL DEFAULT FALSE,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_phone_number_key UNIQUE (phone_number),
    CONSTRAINT users_membership_tier_fkey FOREIGN KEY (membership_tier_id)
        REFERENCES membership_tiers (id) ON DELETE RESTRICT,
    CONSTRAINT users_first_name_not_blank CHECK (char_length(btrim(first_name)) > 0),
    CONSTRAINT users_last_name_not_blank CHECK (char_length(btrim(last_name)) > 0),
    CONSTRAINT users_email_normalized CHECK (email = lower(btrim(email)) AND char_length(email) > 3),
    CONSTRAINT users_phone_e164_mn CHECK (phone_number ~ '^\+976[0-9]{8}$'),
    CONSTRAINT users_password_hash_not_blank CHECK (char_length(btrim(password_hash)) > 0),
    CONSTRAINT users_role_valid CHECK (role IN ('CUSTOMER', 'ADMIN')),
    CONSTRAINT users_status_valid CHECK (status IN ('ACTIVE', 'DISABLED', 'LOCKED')),
    CONSTRAINT users_discount_override_valid CHECK (
        discount_override_percentage IS NULL OR discount_override_percentage BETWEEN 0 AND 100
    ),
    CONSTRAINT users_failed_attempts_nonnegative CHECK (failed_login_attempts >= 0)
);

CREATE INDEX users_membership_tier_idx ON users (membership_tier_id);
CREATE INDEX users_status_created_idx ON users (status, created_at DESC, id DESC);
CREATE INDEX users_search_name_idx ON users (lower(last_name), lower(first_name), id);

CREATE TABLE user_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    label VARCHAR(80) NOT NULL,
    city_or_province VARCHAR(120) NOT NULL,
    district_or_soum VARCHAR(120) NOT NULL,
    khoroo_or_bag VARCHAR(120),
    address_line VARCHAR(300) NOT NULL,
    additional_details VARCHAR(500),
    recipient_name VARCHAR(200) NOT NULL,
    recipient_phone VARCHAR(16) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_addresses_pkey PRIMARY KEY (id),
    CONSTRAINT user_addresses_user_fkey FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT user_addresses_label_not_blank CHECK (char_length(btrim(label)) > 0),
    CONSTRAINT user_addresses_city_not_blank CHECK (char_length(btrim(city_or_province)) > 0),
    CONSTRAINT user_addresses_district_not_blank CHECK (char_length(btrim(district_or_soum)) > 0),
    CONSTRAINT user_addresses_line_not_blank CHECK (char_length(btrim(address_line)) > 0),
    CONSTRAINT user_addresses_recipient_not_blank CHECK (char_length(btrim(recipient_name)) > 0),
    CONSTRAINT user_addresses_phone_e164_mn CHECK (recipient_phone ~ '^\+976[0-9]{8}$')
);

CREATE INDEX user_addresses_user_order_idx ON user_addresses (user_id, is_default DESC, created_at, id);
CREATE UNIQUE INDEX user_addresses_one_default_idx ON user_addresses (user_id) WHERE is_default;
