ALTER TABLE categories
    ADD COLUMN description VARCHAR(1000);

ALTER TABLE brands
    ADD COLUMN description VARCHAR(1000),
    ADD COLUMN display_order INTEGER NOT NULL DEFAULT 0,
    ADD CONSTRAINT brands_display_order_nonnegative CHECK (display_order >= 0);

ALTER TABLE products
    ADD COLUMN product_code VARCHAR(80),
    ADD COLUMN stock_quantity INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN low_stock_threshold INTEGER NOT NULL DEFAULT 5,
    ADD COLUMN membership_discount_eligible BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN new_product BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE,
    ADD CONSTRAINT products_stock_nonnegative CHECK (stock_quantity >= 0),
    ADD CONSTRAINT products_low_stock_threshold_nonnegative CHECK (low_stock_threshold >= 0);

UPDATE products SET product_code = 'PRODUCT-' || id WHERE product_code IS NULL;
ALTER TABLE products ALTER COLUMN product_code SET NOT NULL;
ALTER TABLE products ADD CONSTRAINT products_product_code_key UNIQUE (product_code);

CREATE INDEX brands_admin_order_idx ON brands (display_order, name, id);
CREATE INDEX products_admin_status_idx ON products (status, active, created_at DESC, id DESC);
CREATE INDEX products_admin_inventory_idx ON products (stock_quantity, low_stock_threshold);

CREATE TABLE banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(180) NOT NULL,
    subtitle VARCHAR(500),
    image_url VARCHAR(2048) NOT NULL,
    mobile_image_url VARCHAR(2048),
    link_url VARCHAR(2048),
    link_label VARCHAR(100),
    display_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    starts_at TIMESTAMPTZ,
    ends_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT banners_title_not_blank CHECK (char_length(btrim(title)) > 0),
    CONSTRAINT banners_image_url_not_blank CHECK (char_length(btrim(image_url)) > 0),
    CONSTRAINT banners_display_order_nonnegative CHECK (display_order >= 0),
    CONSTRAINT banners_date_window_valid CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at)
);
CREATE INDEX banners_public_idx ON banners (display_order, id) WHERE active;

CREATE TABLE news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(240) NOT NULL,
    slug VARCHAR(260) NOT NULL UNIQUE,
    summary VARCHAR(600) NOT NULL,
    content TEXT NOT NULL,
    thumbnail_url VARCHAR(2048),
    published BOOLEAN NOT NULL DEFAULT FALSE,
    published_at TIMESTAMPTZ,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT news_title_not_blank CHECK (char_length(btrim(title)) > 0),
    CONSTRAINT news_slug_format CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    CONSTRAINT news_summary_not_blank CHECK (char_length(btrim(summary)) > 0),
    CONSTRAINT news_content_not_blank CHECK (char_length(btrim(content)) > 0),
    CONSTRAINT news_display_order_nonnegative CHECK (display_order >= 0)
);
CREATE INDEX news_public_idx ON news (display_order, published_at DESC, id DESC) WHERE published;

CREATE TABLE admin_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_email VARCHAR(254) NOT NULL,
    action VARCHAR(80) NOT NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id BIGINT,
    details VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_audit_actor_not_blank CHECK (char_length(btrim(actor_email)) > 0),
    CONSTRAINT admin_audit_action_not_blank CHECK (char_length(btrim(action)) > 0),
    CONSTRAINT admin_audit_entity_not_blank CHECK (char_length(btrim(entity_type)) > 0)
);
CREATE INDEX admin_audit_entity_idx ON admin_audit_log (entity_type, entity_id, created_at DESC);
CREATE INDEX admin_audit_actor_idx ON admin_audit_log (actor_email, created_at DESC);
