CREATE TABLE media_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_provider VARCHAR(20) NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    purpose VARCHAR(20) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT media_assets_storage_key_key UNIQUE (storage_key),
    CONSTRAINT media_assets_provider_valid CHECK (storage_provider IN ('LOCAL')),
    CONSTRAINT media_assets_purpose_valid CHECK (purpose IN ('PRODUCT', 'BRAND', 'BANNER', 'NEWS')),
    CONSTRAINT media_assets_storage_key_relative CHECK (
        storage_key !~ '(^/|^[A-Za-z]:|(^|/)\\.\\.(/|$))'
        AND position(chr(92) in storage_key) = 0
        AND char_length(btrim(storage_key)) > 0
    ),
    CONSTRAINT media_assets_original_filename_not_blank CHECK (char_length(btrim(original_filename)) > 0),
    CONSTRAINT media_assets_content_type_valid CHECK (content_type IN ('image/jpeg', 'image/png')),
    CONSTRAINT media_assets_size_positive CHECK (size_bytes > 0),
    CONSTRAINT media_assets_width_positive CHECK (width > 0),
    CONSTRAINT media_assets_height_positive CHECK (height > 0),
    CONSTRAINT media_assets_created_by_fkey FOREIGN KEY (created_by_user_id)
        REFERENCES users (id) ON DELETE RESTRICT
);

CREATE INDEX media_assets_purpose_created_idx ON media_assets (purpose, created_at DESC, id DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX media_assets_creator_idx ON media_assets (created_by_user_id, created_at DESC, id DESC);
