CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(32) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL,
    idempotency_key UUID NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    order_status VARCHAR(32) NOT NULL,
    payment_status VARCHAR(20) NOT NULL,
    payment_method VARCHAR(32) NOT NULL,
    delivery_method VARCHAR(32) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    regular_subtotal NUMERIC(14, 2) NOT NULL,
    discount_total NUMERIC(14, 2) NOT NULL,
    effective_subtotal NUMERIC(14, 2) NOT NULL,
    shipping_total NUMERIC(14, 2) NOT NULL,
    grand_total NUMERIC(14, 2) NOT NULL,
    customer_note VARCHAR(500),
    placed_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT orders_customer_fkey FOREIGN KEY (customer_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT orders_customer_idempotency_key UNIQUE (customer_id, idempotency_key),
    CONSTRAINT orders_number_not_blank CHECK (char_length(btrim(order_number)) > 0),
    CONSTRAINT orders_hash_format CHECK (request_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT orders_status_valid CHECK (order_status IN ('PENDING_CONFIRMATION', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    CONSTRAINT orders_payment_status_valid CHECK (payment_status IN ('UNPAID', 'PENDING', 'PAID', 'FAILED', 'CANCELLED', 'REFUNDED')),
    CONSTRAINT orders_payment_method_valid CHECK (payment_method IN ('CASH_ON_DELIVERY')),
    CONSTRAINT orders_delivery_method_valid CHECK (delivery_method IN ('STANDARD_DELIVERY')),
    CONSTRAINT orders_currency_valid CHECK (currency = 'MNT'),
    CONSTRAINT orders_totals_nonnegative CHECK (
        regular_subtotal >= 0 AND discount_total >= 0 AND effective_subtotal >= 0
        AND shipping_total >= 0 AND grand_total >= 0
    ),
    CONSTRAINT orders_totals_consistent CHECK (
        effective_subtotal = regular_subtotal - discount_total
        AND grand_total = effective_subtotal + shipping_total
    )
);

CREATE INDEX orders_customer_placed_idx ON orders (customer_id, placed_at DESC, id DESC);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_slug_snapshot VARCHAR(260) NOT NULL,
    sku_snapshot VARCHAR(80) NOT NULL,
    product_name_snapshot VARCHAR(240) NOT NULL,
    primary_image_url_snapshot VARCHAR(2048),
    unit_regular_price NUMERIC(12, 2) NOT NULL,
    unit_effective_price NUMERIC(12, 2) NOT NULL,
    discount_per_unit NUMERIC(12, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    line_total NUMERIC(14, 2) NOT NULL,
    CONSTRAINT order_items_order_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT order_items_product_fkey FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
    CONSTRAINT order_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT order_items_money_nonnegative CHECK (
        unit_regular_price >= 0 AND unit_effective_price >= 0 AND discount_per_unit >= 0 AND line_total >= 0
    ),
    CONSTRAINT order_items_line_consistent CHECK (line_total = unit_effective_price * quantity)
);

CREATE INDEX order_items_order_idx ON order_items (order_id, id);
CREATE INDEX order_items_product_idx ON order_items (product_id);

CREATE TABLE order_address_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE,
    label VARCHAR(80) NOT NULL,
    city_or_province VARCHAR(120) NOT NULL,
    district_or_soum VARCHAR(120) NOT NULL,
    khoroo_or_bag VARCHAR(120),
    address_line VARCHAR(300) NOT NULL,
    additional_details VARCHAR(500),
    recipient_name VARCHAR(200) NOT NULL,
    recipient_phone VARCHAR(16) NOT NULL,
    CONSTRAINT order_address_order_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT order_address_required_text CHECK (
        char_length(btrim(label)) > 0
        AND char_length(btrim(city_or_province)) > 0
        AND char_length(btrim(district_or_soum)) > 0
        AND char_length(btrim(address_line)) > 0
        AND char_length(btrim(recipient_name)) > 0
    ),
    CONSTRAINT order_address_phone_e164_mn CHECK (recipient_phone ~ '^\+976[0-9]{8}$')
);
