CREATE TABLE email_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    recipient VARCHAR(254) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    template_name VARCHAR(80) NOT NULL,
    payload JSONB NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ,
    last_error VARCHAR(500),
    CONSTRAINT email_outbox_event_id_key UNIQUE (event_id),
    CONSTRAINT email_outbox_event_type_not_blank CHECK (char_length(btrim(event_type)) > 0),
    CONSTRAINT email_outbox_recipient_not_blank CHECK (char_length(btrim(recipient)) > 3),
    CONSTRAINT email_outbox_subject_not_blank CHECK (char_length(btrim(subject)) > 0),
    CONSTRAINT email_outbox_template_not_blank CHECK (char_length(btrim(template_name)) > 0),
    CONSTRAINT email_outbox_status_valid CHECK (status IN ('PENDING', 'PROCESSING', 'SENT', 'FAILED')),
    CONSTRAINT email_outbox_attempt_count_nonnegative CHECK (attempt_count >= 0),
    CONSTRAINT email_outbox_processed_state_valid CHECK (
        (status = 'SENT' AND processed_at IS NOT NULL)
        OR (status <> 'SENT')
    )
);

CREATE INDEX email_outbox_poll_idx
    ON email_outbox (next_attempt_at, id)
    WHERE status IN ('PENDING', 'PROCESSING');
CREATE INDEX email_outbox_failed_idx
    ON email_outbox (created_at, id)
    WHERE status = 'FAILED';
