ALTER TABLE users
    ADD COLUMN email_verified_at TIMESTAMPTZ,
    ADD COLUMN session_version INTEGER NOT NULL DEFAULT 0;

UPDATE users
SET email_verified_at = COALESCE(updated_at, created_at)
WHERE email_verified;

ALTER TABLE users
    DROP COLUMN email_verified,
    ADD CONSTRAINT users_session_version_nonnegative CHECK (session_version >= 0);

CREATE TABLE email_verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    requested_ip VARCHAR(45),
    CONSTRAINT email_verification_tokens_user_fkey FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT email_verification_tokens_hash_key UNIQUE (token_hash),
    CONSTRAINT email_verification_tokens_hash_format CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT email_verification_tokens_expiry_valid CHECK (expires_at > created_at),
    CONSTRAINT email_verification_tokens_used_valid CHECK (used_at IS NULL OR used_at >= created_at)
);

CREATE INDEX email_verification_tokens_user_active_idx
    ON email_verification_tokens (user_id, created_at DESC)
    WHERE used_at IS NULL;
CREATE INDEX email_verification_tokens_expiry_idx
    ON email_verification_tokens (expires_at)
    WHERE used_at IS NULL;

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    requested_ip VARCHAR(45),
    CONSTRAINT password_reset_tokens_user_fkey FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT password_reset_tokens_hash_key UNIQUE (token_hash),
    CONSTRAINT password_reset_tokens_hash_format CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT password_reset_tokens_expiry_valid CHECK (expires_at > created_at),
    CONSTRAINT password_reset_tokens_used_valid CHECK (used_at IS NULL OR used_at >= created_at)
);

CREATE INDEX password_reset_tokens_user_active_idx
    ON password_reset_tokens (user_id, created_at DESC)
    WHERE used_at IS NULL;
CREATE INDEX password_reset_tokens_expiry_idx
    ON password_reset_tokens (expires_at)
    WHERE used_at IS NULL;
